"""Adding User Model

Revision ID: 59de25f02266
Revises: 94b4362bdb9
Create Date: 2015-09-19 00:50:16.723941

"""

# revision identifiers, used by Alembic.
revision = '59de25f02266'
down_revision = '94b4362bdb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64, collation=u'NOCASE'), nullable=True),
    sa.Column('hashed_password', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
