"""Initial migration

Revision ID: 94b4362bdb9
Revises: None
Create Date: 2015-07-14 00:34:08.966494

"""

# revision identifiers, used by Alembic.
revision = '94b4362bdb9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snippet')
    ### end Alembic commands ###
